### ISSUE TITLE
npm command in watch.js run() function throws error in Windows.

### ISSUE THREAD

**Issue by whindes** [redom/redom-cli#4]
In review of this wonderful framework library (big thanks!), I discovered a potential issue running in Windows 7.

assets/watch.js

`function run (cmd, forever) {`
`//const child = cp.spawn('npm', ['run', cmd]);`
`//Workaround`
`const child = cp.spawn('npm.cmd', ['run', cmd]);`

  `child.stdout.pipe(process.stdout);`
  `child.stderr.pipe(process.stderr);`

 ` if (forever) {`
   ` child.on('exit', () => {`
      `setTimeout(run, 5000, cmd, true);`
   ` });`
 ` }`

 ` return child;`
`} `

**Comment by pakastin** [comment]
Sorry, for some reason I've missed this issue. Fixing now..

**Comment by pakastin** [comment]
Fixed now!

https://github.com/redom/redom-cli/releases/tag/v3.2.1

**Comment by pakastin** [comment]
Thanks for letting know about this and hope you like RE:DOM! 😎👍
