### ISSUE TITLE
Is store.js needed?

### ISSUE THREAD

**Issue by wezm** [redom/redom-cli#6]
Given `@redom/store` is used is `store.js` redundant?

**Comment by pakastin** [comment]
True, however assets were supposed to be just an example..

**Comment by pakastin** [comment]
Hmm..but assets have a separate `package.json` so it could make sense to install `@redom/store` – good idea! 👍

**Comment by pakastin** [comment]
Oh, it's already in use, I'll remove the file 😂

**Comment by pakastin** [comment]
Updated dependencies and removed the file – thanks for letting know! 😉
